# Generated by Django 5.2.5 on 2025-09-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_register_rename_name_products_productname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='contact_no',
            field=models.IntegerField(max_length=20),
        ),
    ]
