# Generated by Django 5.2.5 on 2025-11-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_notification_url_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('order', 'Order'), ('system', 'System')], default='system', max_length=50),
        ),
    ]
