# Generated by Django 5.2.5 on 2025-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('contact_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='productName',
        ),
    ]
