# Generated by Django 5.1.2 on 2025-09-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_products_description_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productName',
            field=models.CharField(max_length=191),
        ),
    ]
